version: 2

sphinx:
  configuration: docs/source/conf.py

build:
  os: ubuntu-lts-latest
  tools:
    python: "3.12"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - watchmedo
    - requirements: requirements-tests.txt
