#!/bin/sh
# Utility script that sets up the development environment for me
# with one command.

python2.7 bootstrap.py
bin/buildout
mv bin bin27

python2.6 bootstrap.py
bin/buildout
mv bin bin26

python2.5 bootstrap.py
bin/buildout
mv bin bin25

ln -s bin27 bin

