[tox]
envlist =
    py{312,311,310,39,38,py3}
    docs
    types
    lint
skip_missing_interpreters = True

[testenv]
usedevelop = true
deps =
    -r requirements-tests.txt
extras =
    watchmedo
commands =
    python -bb -m pytest {posargs}

[testenv:docs]
usedevelop = true
deps =
    -r requirements-tests.txt
extras =
    watchmedo
commands =
    sphinx-build -aEWb html docs/source docs/build/html

[testenv:lint]
usedevelop = true
deps =
    -r requirements-tests.txt
extras =
    watchmedo
commands =
    python -m ruff format src
    python -m ruff --fix src

[testenv:types]
usedevelop = true
deps =
    -r requirements-tests.txt
commands =
    mypy
