.. Global includes, substitutions, and common links.

.. |author_name| replace:: Gora Khargosh
.. |author_email| replace:: gora.khargosh@gmail.com
.. |copyright| replace:: Copyright (C) 2010 Gora Khargosh.
.. |project_name| replace:: ``watchdog``
.. |project_version| replace:: 0.4.0

.. _issue tracker: http://github.com/gorakhargosh/watchdog/issues
.. _code repository: http://github.com/gorakhargosh/watchdog
.. _mailing list: http://groups.google.com/group/watchdog-python


.. _PyInotify: http://github.com/seb-m/pyinotify
.. _kqueue: http://www.freebsd.org/cgi/man.cgi?query=kqueue&sektion=2
.. _FSEvents: http://developer.apple.com/library/mac/#documentation/Darwin/Conceptual/FSEvents_ProgGuide/Introduction/Introduction.html
.. _inotify: http://linux.die.net/man/7/inotify
.. _Mac OS X File System Monitoring Performance Guidelines: http://developer.apple.com/library/ios/#documentation/Performance/Conceptual/FileSystem/Articles/TrackingChanges.html
.. _ReadDirectoryChangesW: http://msdn.microsoft.com/en-us/library/aa365465(VS.85).aspx
.. _GetQueuedCompletionStatus: http://msdn.microsoft.com/en-us/library/aa364986(v=VS.85).aspx
.. _CreateIoCompletionPort: http://msdn.microsoft.com/en-us/library/aa363862(v=VS.85).aspx
.. _pip: http://pypi.python.org/pypi/pip
.. _github: http://github.com/
.. _git: http://git-scm.org/
.. _coverage: http://nedbatchelder.com/code/coverage/
.. _nose: http://somethingaboutorange.com/mrl/projects/nose/0.11.2/
.. _zc.buildout: http://www.buildout.org/
.. _sphinx: http://sphinx.pocoo.org/
.. _Python: http://python.org

.. _pyinotify: http://github.com/seb-m/pyinotify
.. _pywin32: http://sourceforge.net/projects/pywin32/
.. _xcode: http://developer.apple.com/technologies/tools/xcode.html
.. _pyyaml: http://www.pyyaml.org/
.. _argh: http://pypi.python.org/pypi/argh
.. _argparse: http://pypi.python.org/pypi/argparse
.. _select_backport: http://pypi.python.org/pypi/select_backport/
