.. Global includes, substitutions, and common links.

.. |author_name| replace:: Yesudeep Mangalapilly
.. |author_email| replace:: yesudeep@gmail.com
.. |copyright| replace:: Copyright 2012 Google, Inc & contributors.
.. |project_name| replace:: ``watchdog``
.. |project_version| replace:: 2.0.0

.. _issue tracker: http://github.com/gorakhargosh/watchdog/issues
.. _code repository: http://github.com/gorakhargosh/watchdog
.. _mailing list: http://groups.google.com/group/watchdog-python

.. _kqueue: http://www.freebsd.org/cgi/man.cgi?query=kqueue&sektion=2
.. _FSEvents: http://developer.apple.com/library/mac/#documentation/Darwin/Conceptual/FSEvents_ProgGuide/Introduction/Introduction.html
.. _inotify: http://linux.die.net/man/7/inotify
.. _Mac OS X File System Monitoring Performance Guidelines: http://developer.apple.com/library/ios/#documentation/Performance/Conceptual/FileSystem/Articles/TrackingChanges.html
.. _ReadDirectoryChangesW: http://msdn.microsoft.com/en-us/library/aa365465(VS.85).aspx
.. _GetQueuedCompletionStatus: http://msdn.microsoft.com/en-us/library/aa364986(v=VS.85).aspx
.. _CreateIoCompletionPort: http://msdn.microsoft.com/en-us/library/aa363862(v=VS.85).aspx

.. _argh: http://pypi.python.org/pypi/argh
.. _coverage: http://nedbatchelder.com/code/coverage/
.. _file.monitor: http://github.com/pke/file.monitor
.. _fsmonitor: http://github.com/shaurz/fsmonitor
.. _git: http://git-scm.org/
.. _github: http://github.com/
.. _guard: http://github.com/guard/guard
.. _homebrew: http://mxcl.github.com/homebrew/
.. _inotify-tools: http://github.com/rvoicilas/inotify-tools
.. _jnotify: http://jnotify.sourceforge.net/
.. _LibYAML: http://pyyaml.org/wiki/LibYAML
.. _nose: http://nose.readthedocs.org/en/latest/
.. _pip: http://pypi.python.org/pypi/pip
.. _pnotify: http://mark.heily.com/pnotify
.. _pyfilesystem: http://code.google.com/p/pyfilesystem
.. _pyinotify: http://github.com/seb-m/pyinotify
.. _Python: http://python.org
.. _pywin32: http://sourceforge.net/projects/pywin32/
.. _PyYAML: http://www.pyyaml.org/
.. _sphinx: http://sphinx.pocoo.org/
.. _treewalker: http://github.com/jbd/treewatcher
.. _unison fsmonitor: https://webdav.seas.upenn.edu/viewvc/unison/trunk/src/fsmonitor.py?view=markup&pathrev=471
.. _XCode: http://developer.apple.com/technologies/tools/xcode.html
.. _zc.buildout: http://www.buildout.org/
